export const CarouselData = [
    {
      image:
        "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
    },
    {
      image:
        "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pgqgaUx1cJb5oZQQ5v0tNARCeBp.jpg",
    },
    {
      image:
        "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gA49wTJMIr3TUM6fEDkjeGxkYgZ.jpg",
    },
    {
      image:
      "https://www.themoviedb.org/t/p/original/58H6Ctze1nnpS0s9vPmAAzPcipR.jpg",
    },
    {
      image:
        "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/w21lgYIi9GeUH5dO8l3B9ARZbCB.jpg",
    },
    {
      image:
        "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    },
    {
      image:
        "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/kbE3VHOUWWpaE7k7WmReqJYqyh1.jpg",
    },
  ];
  